### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by eyston** [ladderlife/cambo#1]
This milestone is basic feature support -- ready to be used in our products.  I'm going to do these issues.

- [x] update container to match Relay container
  - [x] copy relay container functionality -- mark TODO's as necessary (add to this list)
  - [x] support mock data on container
  - [x] finish up subscriptions on container (refresh subs on change, dispose, etc)
  - [x] make fragments work with variables (init / prepare)
  - [x] allow component to set variables (comp.set-vars)
  - [x] figure out how children and shouldComponentUpdate interact
  - [x] prepare variables -- gets a route argument (make a route key on context ... contents TBD)
- [x] `set` end to end (component -> model -> datasource -> router)
  - [x] `set` in router
  - [x] how do we want to handle optimistic set that datasource doesn't support -- can punt on this
- [x] `call` end to end (component -> model -> datasource -> router)
  - [x] `call` in router
  - [x] main thing is figure out if we need `this` and `refs` queries .. or if we can get away with less
  - [x] allow invalidate messages
- [x] server side datasource #9
- [x] router should allow pathsets as well as path values
- [x] make it work with adv compilation

**Comment by eyston** [comment]
- punt on optimistic set that the datasource ends up not executing
- have `this` and `refs` queries ... can add `root` query for arbitrary stuff easily

**Comment by eyston** [comment]
advanced compilation produces 2 warnings for using `this` -- but works fine!
