### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by eyston** [ladderlife/cambo#2]
Features we know we need and know how to implement but don't need immediately.

- [ ] middleware
 - [ ] update router to take a route-tree -- not routes ... we want route-tree construction outside of router
 - [ ] update route-tree creation to take a construction function -- it will get the match and allow user code to output what the handler map should be (map must still implement `:route` key ... I think)
 - [ ] update route-tree to do two passes -- first one creates the map, second one depth-first traverses the tree calling the fn defined above adding a second arg -- all ascendant matches.  this will allow nice middleware pattern (will give example in ticket)

- [ ] transact -- combination of set + call + queries -- will detail in ticket
